export default {
  searchForms: [{
    formType: 'input',
    disabled: false,
    isRequired: false,
    initialValue: 'ssss',
    key: 'input',
    label: 'input',
    colSpan: 8,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'inputNumber',
    initialValue: 123,
    disabled: false,
    isRequired: false,
    key: 'inputNumber',
    label: 'inputNumber',
    colSpan: 8,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'inputPhone',
    disabled: false,
    isRequired: false,
    key: 'inputPhone',
    label: 'inputPhone',
    colSpan: 8,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'inputMail',
    disabled: false,
    isRequired: false,
    key: 'inputMail',
    label: 'inputMail',
    colSpan: 8,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'inputUnit',
    disabled: false,
    isRequired: false,
    unit: '元',
    key: 'inputUnit',
    label: 'inputUnit',
    colSpan: 8,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'textArea',
    disabled: false,
    isRequired: false,
    key: 'textArea',
    label: 'textArea',
    rows: 5,
    colSpan: 24,
    // placeholder: 'input',
    hasFeedback: true,
  }, {
    formType: 'select',
    disabled: false,
    isRequired: false,
    key: 'select',
    label: 'select',
    placeholder: 'select',
    selectOptions: [
      {
        key: 'select1',
        value: 'select1',
      },
      {
        key: 'select2',
        value: 'select2',
      },
    ],
    hasFeedback: true,
    colSpan: 8,
  }, {
    formType: 'select',
    disabled: false,
    isRequired: false,
    multiple: true,
    key: 'selectMultiple',
    label: 'selectMultiple',
    selectOptions: [
      {
        key: 'select1',
        value: 'select1',
      },
      {
        key: 'select2',
        value: 'select2',
      },
    ],
    hasFeedback: true,
    colSpan: 8,
  }, {
    formType: 'selectDynamic',
    disabled: false,
    isRequired: false,
    key: 'selectDynamic',
    label: 'selectDynamic',
    dictionaryKey: 'selectDynamic1',
    fetchUrl: '/selectLists1',
    colSpan: 8,
    // initialValue: '其他',
    hasFeedback: true,
  }, {
    formType: 'selectDynamic',
    disabled: false,
    isRequired: false,
    multiple: true,
    key: 'selectDynamicMultiple',
    label: 'selectDynamicMultiple',
    dictionaryKey: 'selectDynamicMultiple',
    fetchUrl: '/selectLists1',
    colSpan: 8,
    // initialValue: '其他',
    hasFeedback: true,
  }, {
    formType: 'selectGroup',
    key: 'selectGroup',
    label: 'selectGroup',
    selectOptions: [
      {
        label: 'selectGroup1',
        key: 'selectGroup1',
        childrenOptions: [
          {
            key: 'selectGroup1_1',
            value: 'selectGroup1_1',
          },
          {
            key: 'selectGroup1_2',
            value: 'selectGroup1_2',
          },
        ],
      },
      {
        label: 'selectGroup2',
        key: 'selectGroup2',
        childrenOptions: [
          {
            key: 'selectGroup2_1',
            value: 'selectGroup2_1',
          },
          {
            key: 'selectGroup2_2 ',
            value: 'selectGroup2_2',
          },
        ],
      },
    ],
    hasFeedback: true,
  }, {
    formType: 'selectDynamicGroup',
    multiple: false,
    disabled: false,
    isRequired: false,
    key: 'selectGroupDynamic',
    label: 'selectGroupDynamic',
    placeholder: 'selectDynamic',
    dictionaryKey: 'selectGroupDynamic',
    fetchUrl: '/selectLists2',
    // initialValue: '其他',
    popupContainer: 'scorllArea',
    hasFeedback: true,
  }, {
    formType: 'selectGroup',
    // isRequired: false,
    multiple: true,
    key: 'selectGroupMultiple',
    label: 'selectGroupMultiple',
    selectOptions: [
      {
        label: 'selectGroup1',
        key: 'selectGroup1',
        childrenOptions: [
          {
            key: 'selectGroup1_1',
            value: 'selectGroup1_1',
          },
          {
            key: 'selectGroup1_2',
            value: 'selectGroup1_2',
          },
        ],
      },
      {
        label: 'selectGroup2',
        key: 'selectGroup2',
        childrenOptions: [
          {
            key: 'selectGroup2_1',
            value: 'selectGroup2_1',
          },
          {
            key: 'selectGroup2_2 ',
            value: 'selectGroup2_2',
          },
        ],
      },
    ],
    hasFeedback: true,
  }, {
    formType: 'datePicker',
    showTime: false,
    disabled: false,
    isRequired: false,
    key: 'datePicker',
    label: 'datePicker',
  }, {
    formType: 'datePicker',
    showTime: true,
    disabled: false,
    isRequired: false,
    key: 'datePickerShowTime',
    label: 'datePickerShowTime',
    placeholder: 'datePicker',
  }, {
    formType: 'rangePicker',
    initialValue: ['2018-05-05', '2018-05-25'],
    showTime: false,
    disabled: false,
    isRequired: false,
    key: 'rangePicker',
    label: 'rangePicker',
  }, {
    formType: 'rangePicker',
    showTime: true,
    disabled: false,
    isRequired: false,
    key: 'rangePickerShowTime',
    label: 'rangePickerShowTime',
  }, {
    formType: 'monthPicker',
    disabled: false,
    isRequired: false,
    key: 'monthPicker',
    label: 'monthPicker',
  }, {
    formType: 'timePicker',
    initialValue: '12:12:12',
    disabled: false,
    isRequired: false,
    key: 'timePicker',
    label: 'timePicker',
  }, {
    formType: 'checkboxGroup',
    disabled: false,
    isRequired: false,
    itemColSpan: 4,
    options: [
      { label: 'Apple', value: 'Apple' },
      { label: 'Pear', value: 'Pear' },
      { label: 'Orange', value: 'Orange' },
      { label: 'Apple1', value: 'Apple1' },
      { label: 'Pear1', value: 'Pear1' },
      { label: 'Orange1', value: 'Orange1' },
      { label: 'Orange2', value: 'Orange3' },
    ],
    key: 'checkbox',
    label: 'checkbox',
    colSpan: 24,
  }, {
    formType: 'radioGroup',
    disabled: false,
    isRequired: false,
    itemColSpan: 4,
    options: [
      { label: 'Apple', value: 'Apple' },
      { label: 'Pear', value: 'Pear' },
      { label: 'Orange', value: 'Orange' },
      { label: 'Apple1', value: 'Apple1' },
      { label: 'Pear1', value: 'Pear1' },
      { label: 'Orange1', value: 'Orange1' },
      { label: 'Orange2', value: 'Orange3' },
    ],
    key: 'radioGroup',
    label: 'radioGroup',
    colSpan: 24,
  }, {
    formType: 'upload',
    disabled: false,
    isRequired: false,
    key: 'upload1',
    label: 'upload-listType-text',
    placeholder: 'upload1',
    action: 'sys/file/upload',
    multiple: true,
    acceptType: '*', // .jpg,.png,.pdf,.mp4,.gif,.word
    listType: 'text', // 1:text  2:picture 3:picture-card
    maxFileSize: 10, // 单位是M
    maxFileCounts: 10,
    colSpan: 24,
  }, {
    formType: 'upload',
    disabled: false,
    isRequired: false,
    key: 'upload2',
    label: 'upload-listType-picture-card',
    placeholder: 'upload-listType-picture-card',
    action: 'sys/file/upload',
    multiple: true,
    acceptType: 'image/*', // .jpg,.png,.pdf,.mp4,.gif,.word
    listType: 'picture-card', // 1:text  2:picture 3:picture-card
    maxFileSize: 1, // 单位是M
    maxFileCounts: 10,
    colSpan: 24,
  }, {
    formType: 'upload',
    disabled: false,
    isRequired: false,
    key: 'upload3',
    label: 'upload-listType-picture-card',
    placeholder: 'upload-listType-picture-card',
    action: 'sys/file/upload',
    multiple: true,
    acceptType: 'image/*', // .jpg,.png,.pdf,.mp4,.gif,.word
    listType: 'picture', // 1:text  2:picture 3:picture-card
    maxFileSize: 1, // 单位是M
    maxFileCounts: 10,
    colSpan: 24,
  }],
};
